In [1]:
import numpy as np

In [13]:
myarr=np.array([2,2,4,1,2,6,0],np.int64)

In [3]:
myarr.shape

(7,)

In [6]:
myarr.dtype

dtype('float64')

In [15]:
myarr[1]=97

In [16]:
myarr

array([ 2, 97,  4,  1,  2,  6,  0], dtype=int64)

In [18]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
listarray.dtype

dtype('int32')

In [24]:
listarray.shape #this will give the dimensions of the array

(3, 3)

In [23]:
listarray.size #this will give the total number of element in the array

9

In [25]:
np.array({23,45,18})

array({18, 45, 23}, dtype=object)

In [26]:
zero=np.zeros((10,5)) #this will create 10X5 matrix with each element being 0.

In [27]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
zero.dtype

dtype('float64')

In [35]:
range=np.arange(35) #this will act as a range keyword in python which start from zero and end withs n-1.

In [36]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [39]:
lspace=np.linspace(1,100,50) #not understood

In [40]:
lspace

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [42]:
emp=np.empty((2,6))

In [43]:
emp

array([[1.54779732e-307, 2.97079411e-313, 2.88812355e-291,
        7.19645165e-308, 5.45352918e-312, 2.12199579e-314],
       [0.00000000e+000, 0.00000000e+000, 2.33419538e-313,
        2.12451749e-313, 0.00000000e+000, 0.00000000e+000]])

In [44]:
emp_like=np.empty_like(lspace)

In [45]:
emp_like

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [46]:
ide=np.empty(45)

In [47]:
ide

array([1.65495574e-290, 1.65862548e-290, 3.12369803e-316, 7.51010994e-308,
       6.98151901e-312, 1.55096748e-291, 0.00000000e+000, 3.07994595e-316,
       1.08741044e-311, 6.13256784e-312, 1.55099806e-291, 0.00000000e+000,
       3.12342886e-316, 1.64184404e-306, 5.29321914e-312, 1.54791954e-307,
                   nan, 1.93716618e-317, 4.39134197e+096, 4.44070950e-312,
       1.54788560e-307,             nan, 1.93716618e-317, 8.13143928e+228,
       3.59316982e-312, 1.54785164e-307,             nan, 2.94959424e-316,
       2.18146533e+243, 2.73737457e-312, 1.54781769e-307,             nan,
       1.12646967e-321, 5.60849370e+223, 1.89773159e-312, 1.54778374e-307,
                   nan, 1.12646967e-321, 1.72632863e-306, 1.04959186e-312,
       1.54774979e-307,             nan, 1.12646967e-321, 1.72632868e-306,
       1.81985265e-306])

In [48]:
ide.shape

(45,)

In [49]:
ide.size

45

In [50]:
ide=np.identity(45)

In [51]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [52]:
arr=np.arange(99)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [55]:
arr.reshape(3,33) # the multiplication of parameter must give total number of element in the n-array 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
arr.ravel() #this will give the initial array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
arr.shape

(99,)

#numpy axis

In [60]:
# 1 axis=1d array[0] rows
# 2 axis=2d array[0,1]rows and column
# 3 axis=3d array[0,1,2]
# 4 axis=4d array[0,1,2,3]

In [61]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [62]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [63]:
ar=np.array(x)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
ar.sum(axis=0)#column addition

array([12, 15, 18])

In [68]:
ar.sum(axis=1)#rows addition

array([ 6, 15, 24])

In [69]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [70]:
ar.flat

In [71]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [72]:
ar.ndim

2

In [73]:
ar.size

9

In [74]:
ar.nbytes

36

In [76]:
one=np.array([1,2,3,4,45,678])

In [77]:
one.argmax() #this gives the index of maximum element present 

5

In [78]:
one.argmin()

0

In [79]:
one.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [80]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int32)

In [81]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int32)

In [82]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int32)

In [83]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
ar2=np.array([[1, 1, 0],
       [2, 0, 6],
       [1, 2, 3]])

In [88]:
ar2

array([[1, 1, 0],
       [2, 0, 6],
       [1, 2, 3]])

In [89]:
ar+ar2

array([[ 2,  3,  3],
       [ 6,  5, 12],
       [ 8, 10, 12]])

In [90]:
ar*ar2

array([[ 1,  2,  0],
       [ 8,  0, 36],
       [ 7, 16, 27]])

In [91]:
ar=np.sqrt(ar)

In [92]:
ar

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [94]:
ar.sum()

19.306000526035724

In [95]:
ar.min()

1.0

In [97]:
ar.max()

3.0

In [99]:
np.where(ar>1)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int32),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int32))

In [100]:
np.count_nonzero(ar)

9

In [101]:
import sys

In [106]:
py_ar=[0,4,55,2]

In [103]:
np_ar=np.array(ch_ar)

In [107]:
sys.getsizeof(1)*len(py_ar)

64

In [109]:
np_ar.itemsize*np_ar.size

16